spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_platform?useSSL=false
    password: root
#--------------------------------------------------------------
#客户端SDK配置
api:
  client:
    gateway-host: http://localhost:9000
#--------------------------------------------------------------
#支付宝支付配置（使用中）
alipay:
  return-url: http://localhost:8000/recharge/list
  notify-url: http://bj.frp.one:12000/api/backend/order/notify/order