spring:
  datasource:
    url: jdbc:mysql://xxxxx:3306/api_platform?useSSL=false
    password: xxxxx
#--------------------------------------------------------------
#客户端SDK配置
api:
  client:
    gateway-host: https://xxxxx
#--------------------------------------------------------------
#支付宝支付配置（使用中）
alipay:
  return-url: https://xxxxx/recharge/list
  notify-url: https://xxxxx/api/backend/order/notify/order