spring:
  datasource:
    url: jdbc:mysql://xxx:3306/api_platform?useSSL=false
    password: xxx
#--------------------------------------------------------------
#客户端SDK配置
api:
  client:
    gateway-host: https://api.suki.vin
#--------------------------------------------------------------
#支付宝支付配置（使用中）
alipay:
  return-url: https://api.suki.vin/recharge/list
  notify-url: https://api.suki.vin/api/backend/order/notify/order